### ISSUE TITLE
Enhancement Request: Hex Code requires 6 digits

### ISSUE THREAD

**Issue by chriscam85** [dvargas92495/roam-js-extensions#286]
Hello,
I'd like to request a change to the Hex Code extension. Specifically adding an option flag so that this request does not impact folks using the current version.

I often use the short-form 3-digit hex codes in my css development, so I know it's valid, but in taking my notes within Roam, I prefer using the hashtag and the combination of specific-to-vendor release indicator create situations like: #21A #20B #18D
All of these show the color palette, and this is unintentional.

If possible, can we add a configuration attribute to indicate if the hex code requires 6-digit length? This would default to false.
Thank you much!
Chris

**Comment by dvargas92495** [comment]
makes total sense and seems simple to implement. Thanks for reporting!

**Comment by dvargas92495** [comment]
try out this config @chriscam85!

![image](https://user-images.githubusercontent.com/7143571/101192140-a339d480-3628-11eb-9a12-c1ada803511e.png)

**Comment by chriscam85** [comment]
> try out this config @chriscam85!
> 
> ![image](https://user-images.githubusercontent.com/7143571/101192140-a339d480-3628-11eb-9a12-c1ada803511e.png)

David,
I'm having a hard time figuring out where to put this block. If it matters, I have my page set up where multiple roamjs features are installed in the same block.
Thanks,
Chris

**Comment by dvargas92495** [comment]
ah, just create a page that says `roam/js/hex-color-preview`!
