### ISSUE TITLE
推特与漫游整合插件的视频好像损坏了；The video of the twitter and roaming integration plugin seems to be corrupted

### ISSUE THREAD

**Issue by kunpeng9** [dvargas92495/roam-js-extensions#290]
视频地址= 
https://roam.davidvargas.me/extensions/twitter/
https://roam.davidvargas.me/videos/twitter-references.mp4
![image](https://user-images.githubusercontent.com/44609485/98620165-b619fb80-233f-11eb-906d-e3c9e7e2286c.png)
推特与漫游整合插件的视频好像损坏了；The video of the twitter and roaming integration plugin seems to be corrupted
![image](https://user-images.githubusercontent.com/44609485/98620292-fc6f5a80-233f-11eb-9e3f-aeb561a197dd.png)
其他的视频视频好像都没问题，能看也能下载；Other videos seem to be OK. You can watch them or download them;
提示音轨损坏；Prompt the track is damaged;
![image](https://user-images.githubusercontent.com/44609485/98620644-a3ec8d00-2340-11eb-992f-d54335c6a4c3.png)
再试了一下还是不行；Try again, but still can't;
文件检测失败找不到音频轨或音频轨不可用！File detection failed. Audio track not found or not available!

**Comment by dvargas92495** [comment]
https://roam.davidvargas.me is considered legacy, and will soon be rerouted to https://roamjs.com!
