### ISSUE TITLE
Presentation Mode

### ISSUE THREAD

**Issue by dvargas92495** [dvargas92495/roam-js-extensions#411]
[Source](https://roamresearch.slack.com/archives/C0190JLGDUJ/p1607630343363200)

- Create a {{presentation}} button
- Each child is a slide
- Could design each slide as children of each child
- Clicking the presentation button then puts it in "Present" view with next, previous, exit, etc

**Comment by dvargas92495** [comment]
Should use a presentation library, either this one or otherwise https://swiperjs.com/

**Comment by JimmyLv** [comment]
Hi @dvargas92495 could you please help to add the Twitter embed?

I did initial research, this revealjs plugin should works. 

https://github.com/rajgoel/reveal.js-plugins/tree/master/embed-tweet

**Comment by JimmyLv** [comment]
another plugin https://github.com/evilz/vscode-reveal/blob/master/libs/reveal.js/3.8.0/plugin/embed-tweet/embed-tweet.js

**Comment by dvargas92495** [comment]
Made a separate issue to track it!

**Comment by JimmyLv** [comment]
Hi @dvargas92495 I am falling in with love with this plugin, any plan to support the export function of Reveal https://revealjs.com/pdf-export/

**Comment by kvistgaard** [comment]
@JimmyLv I would support such functionality, although I prefer non-proprietary formats.

By the way, here 's something you might be interested in as well https://roamjs.com/queue/643

**Comment by dvargas92495** [comment]
When I first looked into this, the default export produced by Reveal was very... bad. I'll need to add some extra CSS to be able to replicate what's produced in Roam

PDF export tracked here: 
- https://github.com/dvargas92495/roam-js-extensions/issues/455
- https://roamjs.com/queue/455
