### ISSUE TITLE
Attr Table - Filter Columns

### ISSUE THREAD

**Issue by dvargas92495** [dvargas92495/roam-js-extensions#434]
Be able to view the relevant columns without the noise of all other attributes.

[Source](https://roamresearch.slack.com/archives/CMZMS7FLJ/p1608232876462500)

**Comment by dchelimsky** [comment]
Thanks for adding this to the queue. Do you envision the UI for this being similar to `Default Sort` (e.g. declared in a child block)?

**Comment by dvargas92495** [comment]
I believe so, since the only way to save user-specific data in Roam right now is by using blocks within their graph. There will also probably be a UI element to play with filters before deciding to save a specific one in a block

**Comment by dchelimsky** [comment]
Thanks. Any chance this could order the columns as well? e.g.

```
* {attr-table: [[attr-1]]}
    * Default Sort: ---=Asc
    * Include Columns: attr-1, attr-5, attr-2
```

And that would only include those columns, and they'd be in that order.

**Comment by dvargas92495** [comment]
Yup, this should be possible!
