### ISSUE TITLE
Tag Cycle  — Bug adds spaces after completing the cycle

### ISSUE THREAD

**Issue by caffo** [dvargas92495/roam-js-extensions#466]
Please see the issue: here https://www.loom.com/share/36c4dfcaf34b4ef58783bad4db0944fb

Would you consider this a bug?

**Comment by dvargas92495** [comment]
So this was an artifact of wanting to add an extra space when going from [blank] to tag at the beginning of the block. Which was done to replicate native ctrl+enter functionality.

![image](https://user-images.githubusercontent.com/7143571/103465307-36d5f200-4d08-11eb-96a5-0d29760a12f5.png)

When going from tag to [blank], we can't just remove a whitespace in general bc that could delete a character for some cases. What we can do is delete the whitespace in front IF the tag is in the front of the block and IF that character is a whitespace

**Comment by caffo** [comment]
I think this would be a pretty good fix. And if someone complains about it, we can remove it later. 

Do you want a bounty for it?

**Comment by dvargas92495** [comment]
Nah, I could patch up soon. I don't like the incentives that bounties on bugs imply
