### ISSUE TITLE
Enhancement: Sort references by block creation/edit time

### ISSUE THREAD

**Issue by gvteja** [dvargas92495/roam-js-extensions#486]
I have a project page within which I maintain a running log. As a result, this page could have hundreds or thousands of blocks which refer to various related pages. If I go to one of the related pages, I see tens of references from the same project page.

It would be great if I can sort the references based on the block creation/edit time instead of the page level attributes.

**Comment by dvargas92495** [comment]
Would you want blocks on the same page separated? Meaning let's say I had as references:

[[Page Foo]]
    - block 1 created at t = 0
    - block 2 created at t = 2
[[Page Bar]]
    - block 3 created at t = 1

Would this be the expected sort?
[[Page Foo]]
    - block 1 created at t = 0
[[Page Bar]]
    - block 2 created at t = 1
[[Page Foo]]
    - block 3 created at t = 2

**Comment by gvteja** [comment]
Good question: yes, for my current workflow I would prefer to see blocks in chronological order irrespective of the page. 

If the above is harder to implement, I would be happy even if sorting is contained to within the same page since the number of pages I currently have is <10. So I can manually sort them if the blocks within a page are already sorted.

**Comment by dvargas92495** [comment]
better covered by Query Builder
