### ISSUE TITLE
Add {char-count}

### ISSUE THREAD

**Issue by hillisjd** [dvargas92495/roam-js-extensions#487]
Roam has a built-in {word-count} feature. It would be nice to also have a {char-count}. A good use-case for this is composing tweets in roam to make sure they meet the character limit.

**Comment by everruler12** [comment]
Roam already has built-in {{character-count}} and {{count}} and features.
{{character-count}} includes its own characters in the count, while {{count}} doesn't.

**Comment by hillisjd** [comment]
Awesome, thank you! For some reason, these don't show up for me in the / commands, but they work if I type them out.

**Comment by everruler12** [comment]
Yeah, it seems they're a hidden feature. You could create your own [[roam/template]] to be listed with ;; so you don't have to type them every time.

**Comment by hillisjd** [comment]
Clever, thanks for the idea!

**Comment by kvistgaard** [comment]
> Awesome, thank you! For some reason, these don't show up for me in the / commands, but they work if I type them out.

There are plenty of `{{}}` features which are not included in the /. For example `{{iframe:}}`, `{{or:}}` and many others.
