### ISSUE TITLE
Wikidata search is activated with {{wiki}} instead of {{wd}}

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#488]
The convention for "wiki" is a shortcut to get data from Wikipedia. For example, the shortcode of WP Wiki Toltip is [wiki]  

The convention in Wikidata itself for prefixes and shortcodes is "wd" .

One example is Wikidata query service, where the declaration for the namespace of Wikidata items is wd: `PREFIX wd: <http://www.wikidata.org/entity/>`  

Another example is [Wikidata search extension](https://chrome.google.com/webstore/detail/wikidata-search/ingjkjibhnkhomomlmlabndfmiaejkpn?hl=en-US).   

> To search against Wikidata, type "wd" in the search bar, followed by your search terms.  

Changing `{{wiki}}` to `{{wd}}` will both comply with the established de-facto standard and will free up `{{wiki}}` to be used for Wikipedia

**Comment by dvargas92495** [comment]
I'd be happy ro add `wd`

I'm hesitant to remove `wiki`, since this extension has already been out for awhile and it's in usage now. Changing could be disruptive.

It's not clear to me the difference between Wikipedia and Wikidata - my goal for the extension was to query whichever was more canonical for quick importing into Roam

**Comment by kvistgaard** [comment]
Wikipedia and Wikidata differ substantially. 

First, what connects them. They are both Wikimedia Foundation projects. The content of both is crowdsourced. Wikipedia gets data from Wikidata (along with thousands of other applications that use data from Wikidata). Most Wikipedia articles have Wikidata link (which brings to the respective item, which is a node in the graph identified with a URI, where all values, including labels in various languages, are related with properties, also URIs, which are the edges for the graph)

![image](https://user-images.githubusercontent.com/7572721/104507467-16027c00-55e7-11eb-9656-7fdcc5239b83.png)

Now, some of the major differences.

Wikipedia is simply a wiki using Media Wiki. The content is articles, web pages. The datastore is MySQL.
Wikidata is a knowledge graph, and one of the biggest open knowledge graphs in the world, with over a billion statements growing rapidly. The store is Blazegraph (in fact it's the whole stack which includes Electric search, along with Blazegraph and others). Wikidata supports the RDF model and is queried with SPARQL. 

The result of a Wikipedia search is a web page. 
The results of Wikidata query service are answers and can be of sophisticated queries, including federated queries (see example below) over several independent knowledge graphs. 

This is how each item is presented as UI
![image](https://user-images.githubusercontent.com/7572721/104508430-7f36bf00-55e8-11eb-9164-2556632595b1.png)

And this is the actual data model:
![image](https://user-images.githubusercontent.com/7572721/104508553-b311e480-55e8-11eb-9f83-9b91def90481.png)

One of the interesting things about the model is that there are direct properties and properties of statements. Here's an attempt to explain them with a [sketch and a query.](https://twitter.com/kvistgaard/status/1230506330546409473)

Here and example of a federated query that [combiness data from DBpedia and Wikidata](https://w.wiki/uH5).

**Comment by dvargas92495** [comment]
ahhhh got it! Thanks for the detailed explanation!

So as it stands, the extension _currently_ is a bit of a misnomer and is actually a _wikipedia_ extension. The API calls that the extension makes hits wikipedia.org and not WikiData.

I'd open to enhancements to the current extension to include some wikidata features as well

**Comment by dvargas92495** [comment]
Audit: Won't do
