### ISSUE TITLE
Wiki - works inside (()) but then deletes them

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#511]
... and they have to be added again to have the description collapsed. 

![RoamJS-wiki-parentheticals](https://user-images.githubusercontent.com/7572721/105479027-419afb80-5ca4-11eb-961d-527a76d21c26.gif)

**Comment by dvargas92495** [comment]
I consider this to be a bug and will work on this today

**Comment by kvistgaard** [comment]
For it doesn't work. In fact, it's worse: when using (({{wiki}})), it just keeps the button WIKI, or -- if I press "Enter" after wiki -- creates block bellow.

**Comment by kvistgaard** [comment]
Initially, after reloading Roam it didn't work, but after restarting the browser, it works.

**Comment by dvargas92495** [comment]
It uses the new write api, so probably needed to check for updates
