### ISSUE TITLE
Date Format on charts doesn't work

### ISSUE THREAD

**Issue by raph90** [dvargas92495/roam-js-extensions#512]
I spent about 2 hours trying to troubleshoot this this morning but was unable to find the answers. 

When I use {{line}} or line-chart and set the X-Axis to time, the date format input appears, but I'm unable to change the value.

I tried going into the src files and swapping out the component for a basic input, but even then I couldn't update the value. 
I removed all other custom javascript from my graph, as well as updated all dependencies, but still no dice. 

If someone else could have a look at this, or tell me if the code is working on their graph that would be awesome.

**Comment by dvargas92495** [comment]
Did you try to set it as a date format attribute as a child of the graph?

![image](https://user-images.githubusercontent.com/7143571/105499001-dc88db00-5c8e-11eb-8b6b-7aab703126ad.png)

[Source](https://roamjs.com/docs/extensions/charts)

When you do, you'll have to "refresh" the chart so that it takes in the new configuration by clicking into the block and clicking out

**Comment by raph90** [comment]
Ah I didn't try that! I'll have a go now, thanks @dvargas92495.

**Comment by mandliya** [comment]
Hello @raph90  and @dvargas92495 

I am seeing a weird issue with date format and I can't seem to get it work. I could be doing something completely wrong, and apologies if I am misunderstanding something. 

Here is an example. Although I use `yyyy-MM-dd` I also get time.

![image](https://user-images.githubusercontent.com/4503796/120965688-12000380-c71a-11eb-9d45-7ae9622ccffc.png)

When I try other options mentioned in the [specification](https://date-fns.org/docs/format) I get very weird output.

![image](https://user-images.githubusercontent.com/4503796/120966215-c863e880-c71a-11eb-9cb4-14c02a3ea66e.png)

I tried  `date-fns parse` in the below playground for same input, things seems to have worked.
https://stackblitz.com/edit/date-fns-playground-mw8th8?file=index.ts

I am not JS newbie, so I might be getting it wrong, in code we seem to be not passing the `date` but `string` in the parse call [here](https://github.com/dvargas92495/roam-js-extensions/blob/95137cb72fe406be20485a89eee098b623323712/src/components/Charts.tsx#L63)

**Comment by dvargas92495** [comment]
> Although I use yyyy-MM-dd I also get time.

Not sure what you mean here. This image seems like expected value?

> When I try other options mentioned in the specification I get very weird output.

This seems like it's failing to parse your data with the `EEEE` format

The format field is meant to match whatever you input, that way the extension knows how to handle it

**Comment by mandliya** [comment]
Thank you David for the reply. I see how I was misinterpreting it.
