### ISSUE TITLE
Allow verifying extension hash

### ISSUE THREAD

**Issue by jtrakk** [dvargas92495/roam-js-extensions#519]
I would like to make sure that I'm executing the same code today as I was yesterday. For example if the url example.com/roamextension-v1.2.3.js gets taken over by hackers and roamjs goes to download the url, I'd like roamjs to raise an error instead of executing malicious code. A good solution to this is adding a `sha256` parameter, so the hash of the code can be verified before executing. If it gets the wrong hash it can say 

```
error: hash failed to verify:
expected <hash1> 
got <hash2>
```

**Comment by dvargas92495** [comment]
I'm hesitant to add this to latest, to keep all users up to date with latest scripts.

I definitely see adding this once versions are implemented: https://github.com/dvargas92495/roam-js-extensions/issues/13

**Comment by dvargas92495** [comment]
versions are live
