### ISSUE TITLE
Show page header only once for adjacent results from the same page

### ISSUE THREAD

**Issue by jtrakk** [dvargas92495/roam-js-extensions#520]
Related to https://github.com/dvargas92495/roam-js-extensions/issues/486

For the case of queries
![image](https://user-images.githubusercontent.com/43392409/105670986-d5ccb480-5e96-11eb-9c7e-87953d8f9859.png)

On a page with many matching blocks, the page title appears many times and is distracting. I would like to have the page header appear only once:

![image](https://user-images.githubusercontent.com/43392409/105671830-31e40880-5e98-11eb-9526-af6f4a96ba39.png)

I think a more flexible approach than the current one would be having a series of sorting criteria, such as 

```
Sort: [Page Title, Block Title, Block Created]
```

maybe with an additional setting like

```
Merge Blocks Under Page: True
```

**Comment by dvargas92495** [comment]
I really like the `Merge Blocks Under Page` idea! I could also see `Default Sort` taking an array of sorting criteria

I think you want to have a flag to either sort page or blocks - the two have pretty different sorting logic and not immediately obvious how you would interleave them

**Comment by dvargas92495** [comment]
Query Builder is now the go to query/sorting/view management extension
