### ISSUE TITLE
Presentation -- short-cut to start/resume presenting

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#522]
Especially relevant in connection with #522 when the [PRESENT] button is faraway up the page.

**Comment by dvargas92495** [comment]
I would say this is a duplicate - what's the difference? or are you thinking of a keyboard shortcut?

**Comment by kvistgaard** [comment]
Yes.

**Comment by dvargas92495** [comment]
Closing, but this would be quick to implement if interest resurfaces
