### ISSUE TITLE
Mindmap - Shows extra headers that dont exist as a block - Issue

### ISSUE THREAD

**Issue by orkhan10** [dvargas92495/roam-js-extensions#524]
![Screenshot 2021-01-25 at 14 17 29](https://user-images.githubusercontent.com/18570936/105711137-6a2b2b80-5f18-11eb-8e57-b7d5da85d7d2.png)

**Comment by orkhan10** [comment]
> Is this in reference to those stray branches? I agree that that's a bug

Yes exactly.

**Comment by dvargas92495** [comment]
I think this _may_ have been accidentally fixed with the latest refactor but I'm not sure. Could you
- Refresh Roam and see if it's still an issue
- If so, paste the raw markdown that causes the issue here so I could try to replicate it locally

**Comment by orkhan10** [comment]
[Archive.zip](https://github.com/dvargas92495/roam-js-extensions/files/5875812/Archive.zip)

Still exists. 
I cut out an excerpt from the original so that it would not be too large. (you can find the markdown and the screenshots in the zip file)
The screenshots show that main branch and the branches on the top have those stray branches but the bottom ones don't.

**Comment by orkhan10** [comment]
Also wanted to ask whether it is possible to make it dark mode friendly? (Change the background according to the system setting, like the themes do it with css)

**Comment by dvargas92495** [comment]
ok check out latest!

For theming - The root node has an id `roamjs-mindmap-container`. I'd prefer to customize themes with roam/css over the extension itself

**Comment by orkhan10** [comment]
![Screenshot 2021-01-27 at 12 06 11](https://user-images.githubusercontent.com/18570936/105982811-19424100-6098-11eb-80d5-0bbf018eda74.png)

Normal Blocks after H3 Blocks are not visible...

**Comment by orkhan10** [comment]
![Screenshot 2021-01-27 at 12 07 44](https://user-images.githubusercontent.com/18570936/105982967-51498400-6098-11eb-962d-afaab5fa7151.png)
Clicking doesn't help either

**Comment by orkhan10** [comment]
@dvargas92495 
Are you planning on maintaining this extension? I would like to know whether to wait for this or not.
Best!

**Comment by dvargas92495** [comment]
Agh yea whoops sorry, I let this get buried. Will work on it today!

**Comment by orkhan10** [comment]
Thanks a lot David. When I was using Notion I really wanted to a Mindmap function, but it was impossible. I got excited when I saw your extension. Hope you can maintain it.

**Comment by dvargas92495** [comment]
ah this issue is on a different page then the one you included above. I can't repro the issue, could you paste in the markdown where you're seeing the issue?

**Comment by orkhan10** [comment]
[Roam-Export-1612545546616.zip](https://github.com/dvargas92495/roam-js-extensions/files/5934167/Roam-Export-1612545546616.zip)

**Comment by orkhan10** [comment]
I exported the whole page as markdown. Once you open the Mindmap you are going to see that you cant open the items after H3 for example:     3. What is a Stock?

**Comment by dvargas92495** [comment]
Fix should be live!

**Comment by orkhan10** [comment]
Thank you David. It has fixed it.
Now that these items are shown, I see that images do not fit into branches. I thought the pictures were big, thats why they dont fit. However, that is not the case. I made smaller but it made no changes on the mindmap.

**Comment by dvargas92495** [comment]
Yea image resize would be an enhancement for this extension to support it

**Comment by orkhan10** [comment]
In somebranches there are extra connectors like in the picture. They don't disturb the functionality. Just wanted to let you know! Peace!

![Screenshot 2021-02-08 at 23 59 01](https://user-images.githubusercontent.com/18570936/107292196-ba9e9f00-6a69-11eb-9669-ff66847a51b6.png)
