### ISSUE TITLE
Query-sorting criteria: attribute value

### ISSUE THREAD

**Issue by jtrakk** [dvargas92495/roam-js-extensions#528]
I would like to sort query results by a certain attribute or list of attributes.

**Comment by dvargas92495** [comment]
Have you tried using `{{attr-table}}`s yet?

https://roamjs.com/docs/extensions/attr-tables

**Comment by jtrakk** [comment]
I don't think that's what I'm looking for. I want to keep the same query interface but reorder the blocks by the value of their `Priority::` and `Due Date::` attributes.

**Comment by dvargas92495** [comment]
Query Builder supports this now
