### ISSUE TITLE
Presentation -- choose the next slide to go to

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#532]
The Roamy way to that would be though block references
![image](https://user-images.githubusercontent.com/7572721/105978953-65d74d80-6093-11eb-9606-92170de186d8.png)

**Comment by dvargas92495** [comment]
The library I'm using has the capability to go in two dimensions. What do you think about that idea?

![image](https://user-images.githubusercontent.com/7143571/106045499-fff8bf00-60ae-11eb-9bce-1b4101d47c8b.png)

**Comment by kvistgaard** [comment]
I gave an example of a particular case with two branches. A slide a can have, say, 5 bullets, and each bullet can be a reference to a block which is a slide. Of course, a more advanced feature is when the referred slide is in another presentation. 

And overall the idea is to benefit more from Roam features. Before Roam Presentation, and still now, I often use Roam as is, for presenting, so jumping to another block and back is the most natural thing.

In terms of the expected frequency of utilisation, is by not as important as, say, presenting from a slide.

**Comment by dvargas92495** [comment]
Moved to #745
