### ISSUE TITLE
Image Tagging

### ISSUE THREAD

**Issue by everruler12** [dvargas92495/roam-js-extensions#538]
`DOUBLE CLICK` **Trigger** doesn't work now that Roam displays image gallery when image is clicked.
`SHIFT CLICK` works, but still opens the image gallery.
`ICON CLICK` seems to be the best solution. Suggestion is to set it to default, or let that be the only trigger. And to only show when mouseover image, like the edit icon.

I've updated the instructions at https://roamresearch.com/#/app/roam-depot-developers/page/3fGX8Hbfa

Another idea for the refactor is when script runs for the first time, createPage() [[roam/js/image-tagging]] and createBlock() `Trigger:: {{or:ICON CLICK | SHIFT CLICK}}`

**Comment by dvargas92495** [comment]
> Another idea for the refactor is when script runs for the first time, createPage() 

This is something I want to do with a bunch of extensions.

I agree, ICON should be the default now with Roam's changes
