### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by dvargas92495** [dvargas92495/roam-js-extensions#541]
Use the Daily Notes pages with some filtering features to render a timeline view of a topic. Some motivating links:

- https://codecanyon.net/item/first-responsive-timeline/19352502
- https://timeline.knightlab.com/
- https://github.com/arcazj/openbexi_timeline
- https://propublica.github.io/timeline-setter/

**Comment by kvistgaard** [comment]
Another inspiration -- any query on Wikidata with time properties. See for example [this one](https://twitter.com/kvistgaard/status/1230506330546409473).
