### ISSUE TITLE
TODO-trigger -- when single value leaves a `#` in [[DONE]]

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#544]
I have declared
Replace Tags:: #toShare, #shared | #toTweet, #tweeted | #toWatch, #watched | #toCheckOut, #checked | #get | #followUp |

expecting that for #get and #followUp , the will be dimple deleted on [[DONE]]

instead, a `#` is left.

Then going back to [[TODO]] places:

#[[undefined]] #[[undefined]] #[[undefined]]

**Comment by dvargas92495** [comment]
That's a bad bug, following up now
