### ISSUE TITLE
TODO-trigger -- apply rule of parent tag on child TODOs

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#547]
Example

- #toDecide
   - [[TODO]] First
   - [[TODO]] Second
   - [[TODO]] Third

triggers
- #toDecide 
   - [[TODO]] First
   - [[TODO]] Third
- #Decided
   - [[DONE]] Second 

(if there is more than one parent tag included in `Replace Tags::`,  should work only for the first)

while inline works as expected:
- [[TODO]] Something #toDecide -->  - [[TDONE]] Something #Decided

**Comment by dvargas92495** [comment]
I like this as a new configuration - `Parent Tags`

This sort of feature has been made far more easier to do with the write API

**Comment by dvargas92495** [comment]
Audit: Won't do - Could revisit if interest resurfaces
