### ISSUE TITLE
Presentation -- slide URI

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#554]
Currently, during a presentation, the page URI doesn't change.

Ideally, it should change in a way to open the respective block as a slide (as it is in Reveal.js and Google slides), 
or
at least go to the respective block.

This is related to #532 but should work from anywhere, not just inside a presentation. 
I mean, if this generic capability is present, then the specific case of #532 is dissolved.

**Comment by dvargas92495** [comment]
I'm not sure if we could change the URI without Roam itself then handling it

**Comment by kvistgaard** [comment]
Well, the URI is there. If you go to each block-slide and focus on it, it will show the URI in the address bar. I thought now with the API, this "focus-on-block" should be evocable. It doesn't need necessarily to open the slide in presentation mode. Having something which is at the same time unique ID and provides access to the resource, e.g. https://roamresearch.com/#/app/help/page/XT6nyeACa , is very valuable.

**Comment by dvargas92495** [comment]
Right but I think what will happen is that Roam will navigate to that Roam block, removing the presentation from the current page.

we might be able to use query params: `?block=XT6nyeACa`

**Comment by kvistgaard** [comment]
What is like in Reveal.js is that I can share a [link to a particular slide](https://rajgoel.github.io/reveal.js-demos/anything-demo.html#/1/5/3) and I thought, that should possible, and even easier,  in Roam.

**Comment by dvargas92495** [comment]
Yea they're making use of the hash to handle everything on the user side `#/1/5/4`.

This works for sites that aren't using this. But Roam is _already_ reading this and making its own determination about how to handle it: `#/app/help/page/XT6nyeACa`

So basically, we have to find a way to edit the URI that Roam will ignore
