### ISSUE TITLE
TODO Trigger -- new tags for [[DONE]] state not applied retroactively

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#563]
For example, I changed my old tag #m to #toMail and now I have plenty of old `[[DONE]] #toMail` blocks, while I want all such blocks, old a new, to be either `[[TODO]] #toMail` or `[[DONE]] #Mailed`.

**Comment by dvargas92495** [comment]
I think there's a Roam hack you could do to fix this:

1. Create a `[[[[DONE]] #toMail]]` page
2. Rename that page to `[[[[DONE]] #Mailed]]`
3. Delete the page

**Comment by dvargas92495** [comment]
Audit: Won't do
