### ISSUE TITLE
Presentation -- title slide layout

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#577]
Either treat the first child-block as title or -- better -- introduce a title layout to be applied {} to an arbitrary block.

**Comment by dvargas92495** [comment]
The blocks on the first level are treated as the title. What problems are you running into with this convention?

**Comment by kvistgaard** [comment]
Not slide title, but title slide.

**Comment by dvargas92495** [comment]
Ah, if there are no children, the slide acts as a title slide

**Comment by kvistgaard** [comment]
True but 99% of the presentations I've seen or [delivered](https://www.slideshare.net/kvistgaard/edit_my_uploads), the title slide has at least
{TITLE}
{SUBTITLE}
{PRESENTER NAME} | {DATE}

**Comment by kvistgaard** [comment]
It would be nice to optionally add an image to title slide and control the font and color of different elements
