### ISSUE TITLE
Presentation - Vertical Slides

### ISSUE THREAD

**Issue by WillPlatnick** [dvargas92495/roam-js-extensions#585]
Idea: Ability to use Vertical Slides in the Presentation Extension.

Use Case: In some case, bullets make sense to show. At other times, bullets are topics to explore in the presentation. For example, I have a long list of examples to explore in a presentation. In Roam, I've nested all my examples under an "Examples" bullet point. Rather than shoving 20 bullets into a slide, I'd like to use the Vertical Slide feature of reveal to do individual vertical slides for each nested bullet point.

I think it makes sense for this to be a configuration option in the slides command. 

Example: Logseq implemented this really well. Go to [any page](https://logseq.com/#/page/how%20to%20take%20dummy%20notes%3F) and click the play button. 

![CleanShot 2021-02-14 at 08 39 16](https://user-images.githubusercontent.com/1935688/107878365-246edc80-6ea0-11eb-9bca-0fa833a1d7ef.png)

I'd like to attach a $20 bounty to this.

**Comment by dvargas92495** [comment]
Adding comment from #595 to tackle here:

When expanding a bullet, often part of the content is not visible. Reveal.js has vertical navigation but it works for defined slides. In the case of Roam Presentation, it needs to work more like page down/up.

**Comment by dvargas92495** [comment]
Moved to #745
