### ISSUE TITLE
Chart - Graph Slider Data

### ISSUE THREAD

**Issue by WillPlatnick** [dvargas92495/roam-js-extensions#586]
I would love the ability to chart slider data pulled from references to a page in order to better understand patterns in my data.

Use Case: I have a Smartblock that I use as the base of my daily page. I have 3 sliders I use as mood trackers. Each slider is nested under a link like [[How are you feeling?]]. I would like to place a chart on the [[How are you feeling?]] page that graphs the results of the referenced sliders, by date. When you mouse over a day's data point, I'd like the contents of the sub-block to be displayed. I use the sub-block to explain why I rated myself as I did.

Example Data Structure:
![CleanShot 2021-02-14 at 09 00 42](https://user-images.githubusercontent.com/1935688/107878847-4322a280-6ea3-11eb-8ae7-a0c3e52d771a.png)
 
I'd like to attach a $50 bounty to this.

**Comment by dvargas92495** [comment]
Instead of as a new extension, how do you feel about this being an enhancement on charts?

https://roamjs.com/docs/extensions/charts

**Comment by WilliamDurin** [comment]
If that’s where you think it’s best, that’s fine by me.
