### ISSUE TITLE
REPL in Roam

### ISSUE THREAD

**Issue by dvargas92495** [dvargas92495/roam-js-extensions#588]
From a conversation with [Scott Block](https://twitter.com/insidetheblock)

Building a way to manage fast feedback loop in roam/js development. Other hackers currently using Smart Blocks to achieve this. Some features:

- Hot reloading from URL and Roam block
- Clear active event listeners and observers
- Dependency Management

Explore the possibility of integrating repl.it, either through iframes or otherwise

**Comment by simion-iulian** [comment]
Hey!

I've had a look at Klipse which my help embedding a REPL: https://blog.klipse.tech/clojure/2016/06/07/klipse-plugin-tuto.html

Sorry, I'm not familiar with how to integrate with roam/js (I've started using Roam 3 days ago and I already want a Clojure REPL block). 

What example extension would be best to look at to get an idea of how I could embed Klipse?

Thank you!

**Comment by dvargas92495** [comment]
I would look at any extension that uses `createButtonObserver` - It's the function that allows be to replace any block of the form `{{repl}}` with any other component of your choice.

I'd take a look at `Maps` and `Charts` for example
