### ISSUE TITLE
Presentation -- a slide  with {layout:Image Left} and with only the image block, disables presenting

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#590]

**Comment by dvargas92495** [comment]
What's the use case here? Why have a layout:image left if there is no text instead of just having the image without layout?

**Comment by kvistgaard** [comment]
The use case is: prevent waste of time, panic before meeting etc
Here's the story: I had no idea why pressing [PRESENT] brought no results. Then, after trying out different things (it took some time), I saw that I still haven't put text on one slide, only image. I could relate that to not being able to present at all, but I turned it off and it worked. 

If the issue with not being able to present is not an easy fix, then just a doc note will do.
