### ISSUE TITLE
Presentation -- Shift-up produces vertical stripe on the left side

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#596]

**Comment by dvargas92495** [comment]
Not sure what you mean by this? Are you saying that while pressing shift-up during present mode, a vertical stripe is undesirably produced on the left side?

**Comment by kvistgaard** [comment]
Yes. Can't you reproduce it?

**Comment by dvargas92495** [comment]
Yea I don't see it. Could you post a screenshot?

**Comment by dvargas92495** [comment]
Audit: Won't do
