### ISSUE TITLE
Presentations -- sections: set optional one or more hidden levels above the slide level

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#611]
Allow an optional way to organise slides in sections. The default mode should still be without sections, and then adding, say {sections:2} should allow two hidden block levels above the slide level. 

Unlike Powerpoint where sections are only one level, here they can be more, although in practice I can't imagine more than 2 will be used for normal presentations. For training courses, it's likely to have more than 2.

**Comment by dvargas92495** [comment]
Moved to #745
