### ISSUE TITLE
Presentation -- {hide} to work also on blocks

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#614]
There are plenty of use cases for that but three stand out:

1. Instead of making dedicated presentations, just turn some of the blocks in a page by nesting them under {{slides}} block and add {hide} for all blocks within the slide, below which I don't want to keep/add content but not show it while presenting;
2. For adding notes to be used before and after the presentation, not during (at least until there is a way to be shown but only to the presenter);
3. Switching on and off parts of the same slides depending on the audience.

**Comment by dvargas92495** [comment]
Do you find collapsing blocks to hide blocks to be insufficient?

**Comment by kvistgaard** [comment]
Yes, because it doesn't work for {collapsible}, and rightly so.
Then from a usability point, even for non{collapsible} presentation, people often collapse and expand all on top. When reusing the same content for presentation, it is a waste of time to "tune" for presenting after collapse-all, expande-all is applied, by going to each slide choosing the desired presentation depth.

**Comment by dvargas92495** [comment]
Ok so I think I'm going to use this task to actually remove the functionality that collapsing hides content from the slide after discussing with other users, and allow only `{hide}` to support this

**Comment by kvistgaard** [comment]
You said somebody had a case in support of the other behaviour. But  guess
you checked the impact with them.

**Comment by dvargas92495** [comment]
Yup exactly checked with them first!
