### ISSUE TITLE
Control key incorrectly detected on macOS

### ISSUE THREAD

**Issue by montasaurus** [dvargas92495/roam-js-extensions#621]
The function checking for the control key is actually checking for the [Command (⌘) key on macOS](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey):  https://github.com/dvargas92495/roam-js-extensions/blob/9d6cff39d3ef46468c0a044ceaa2596c3a718840/src/entry-helpers.ts#L754-L755

The documentation for the [mouseless](https://roamjs.com/docs/extensions/mouseless) and [todont](https://roamjs.com/docs/extensions/todont) extension say that the keyboard extension uses the Control key.

Either the function should check for the Control key (by just removing the Apple-specific logic in the above function and check for `e.ctrlKey`) or the documentation should reflect the different behavior on macOS.

My preference would be to use the Control key. I'm happy to submit a PR to fix it.

**Comment by dvargas92495** [comment]
I think I want to update the documentation - I was told by previous mac users to use cmd which is where this change came from. Particularly for todont, I want it to mirror the TODO/DONE functionality.

Thanks for pointing it out!
