### ISSUE TITLE
Update docs to provide clearer instructions on configuration

### ISSUE THREAD

**Issue by shaunagm** [dvargas92495/roam-js-extensions#625]
I couldn't get the [github extension](https://roamjs.com/docs/extensions/github) to work. After much experimentation I figured there must be something wrong with the configuration, so I started reading through the docs for the other extensions one by one until I found one ([pull references](https://roamjs.com/docs/extensions/pull-references)) which actually showed how configuration is supposed to work. Ten seconds later, I had a working Github extension.

If all the extensions use the same configuration syntax, you might consider writing up a very short explainer. You could even link it from the individual extension docs.

I'm happy to submit a PR with these changes, but would need you to specify exactly how configuration works and how you'd want to incorporate the information into the docs (put it on the index page? give it its own page? link to it from individual extensions docs pages?) so it might actually be less work for you to just do yourself. Whatever you prefer.

**Comment by dvargas92495** [comment]
I started configurations using the Roam Attributes, but recently have been transitioning away to just have tree configuration and not require attributes. Because of this, I would rather just improve the pull references and GitHub docs to be a lot clearer
