### ISSUE TITLE
Mindmap - Image Improvements

### ISSUE THREAD

**Issue by dvargas92495** [dvargas92495/roam-js-extensions#626]
- Making consistently smaller
- Open Preview on Click
- Optionally turn off

DM [Source](https://twitter.com/o_allahverdi)

**Comment by orkhan10** [comment]
Could you please also add above as another request to make text highlight also to be transferred to the mindmap? If you find it reasonable and doable.

![6F8F47B3-49A2-44B8-9B0B-FD5C18836BFB](https://user-images.githubusercontent.com/18570936/115812061-10d87880-a3f1-11eb-857b-c97f0a65c744.png)

**Comment by dvargas92495** [comment]
yup, should be doable!
