### ISSUE TITLE
Page Synonyms -- Roam error after Alt-A

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#627]
When selection Alias Page synonyms, I get "Roam wasn't built in a day, and we've got an error", either right away or when clicking to the created alias.

**Comment by dvargas92495** [comment]
This is why this config option was created: 
![image](https://user-images.githubusercontent.com/7143571/109428908-2c15a180-79c7-11eb-836f-4a75b0c3d3ee.png)

This is a bug on Roam's end that I'm trying to pester them to fix
