### ISSUE TITLE
Local setup guide

### ISSUE THREAD

**Issue by makalaaneesh** [dvargas92495/roam-js-extensions#63]
Hey @dvargas92495 , 

Really excited by what you're building! Wanted to set the project up locally to test out a few ideas that I had! It would be great to document instructions for local setup and connecting with roam.

I don't know much about javascript/typescript so I have no idea where to start 😅

**Comment by makalaaneesh** [comment]
Managed to set it up :) will raise a PR.

**Comment by dvargas92495** [comment]
Hey @makalaaneesh !

I was hoping to flesh out https://github.com/dvargas92495/roam-js-extensions/blob/master/CONTRIBUTING.md as soon as someone expressed interest, so thanks for reaching out!

There is so "local setup" per se. My flow is that each PR deploys to `https://davidvargas.me/${PR_NUMBER}/${script.js}`. This doesn't work as well for forks, but we could talk more on how to facilitate that.

Another option is to `npm install` and then `npm run build` locally, then copy and paste the minified output into Roam for testing. Let me know if there's anything else I could do to help!

**Comment by makalaaneesh** [comment]
Ah, okay! How do you test your code before creating a PR though? Do you run it directly in your browser console?

Here are the steps I had followed:

- Install npm
    - `brew install node`
- Install dependencies
    - `npm install`
- Build Project
    - `npm run build`
- Serve the JS 
    - `npm install -g http-server`
    - `http-server` in the project dir
- setup src in roam/js to `http://127.0.0.1:8080/build/${name}.js`

**Comment by dvargas92495** [comment]
My dev cycle has been testing in the PR... haha. So there was no testing locally. Basically deployed to the branched path and test in my personal roam directly
