### ISSUE TITLE
Twitter - Daily Feed

### ISSUE THREAD

**Issue by dvargas92495** [dvargas92495/roam-js-extensions#635]
Configure with a `Feed` Block in your Daily Notes Page

Pulls in likes or bookmarks from the previous day, you could pick and choose which to import upon initial navigation to the daily notes page

**Comment by kvistgaard** [comment]
David, this is very useful but I make many refreshes a day, and every time the dialogue appears. Can this be either store the fact that there was already a response (import or cancel) and not appear again for the day?
And/or option to evoke it with a ;; at the page (and time) you want.

**Comment by dvargas92495** [comment]
haha yea it's not ready yet! Was going to solve the frequent appearance problem today
