### ISSUE TITLE
Twitter -- not clear documentation re:images 

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#640]
It's not clear if the send the image, the page should be in
a) the same block as the text, and if there
 -- directly after, or with
 -- soft linebreak
b) sibling block 
c) child block of the text (=grandchild of the block with {[[Tweet]]}}

**Comment by dvargas92495** [comment]
added the following:

![image](https://user-images.githubusercontent.com/7143571/111937937-3e9f6a00-8a9f-11eb-8104-afe788618fe6.png)
