### ISSUE TITLE
Presentation -- in numbered list mode, when changed to H1,2,3, the number remain in paragraph style

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#648]

**Comment by dvargas92495** [comment]
This is also a bug, will take a look

**Comment by dvargas92495** [comment]
![image](https://user-images.githubusercontent.com/7143571/113015117-36a09380-914b-11eb-890e-bf4c674275b8.png)

Hm I'm seeing the heading rendering in the appropriate style? do you have example markdown I could use to reproduce?
