### ISSUE TITLE
Presentation -- after soft return, the following paragraphs appear formatted as code block

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#649]

**Comment by dvargas92495** [comment]
This is a bad bug, will get on it today

**Comment by dvargas92495** [comment]
![image](https://user-images.githubusercontent.com/7143571/113014971-153fa780-914b-11eb-97f6-ce4542541a31.png)

I just tried testing and it seemed to put the entire text into one line instead of a code block. Do you have example markdown I could use to reproduce?
