### ISSUE TITLE
Twitter -- make the block indicated none like or cancelled options

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#651]
Currently, when the daily feed is cancelled, this creates two blocks #[[Twitter Feed]] with Child cancelled or if no tweets like just #[[Twitter Feed]]. And every time I need to delete them. Could they be set as an option or the current script is checking them to avoid looping?

**Comment by dvargas92495** [comment]
The current script is checking them to avoid looping. If not on the DNP, we need to insert a block _somewhere_ to indicate that we've already showed the feed to the user and shouldn't show it again
