### ISSUE TITLE
Serendipity crashed page

### ISSUE THREAD

**Issue by tfiers** [dvargas92495/roam-js-extensions#652]
Hiya, congrats on the polished project and the readable code.

I tried out Serendipity; it crashes my Roam: unresponsive page and high cpu usage, for as long as I can wait (had to uBlock `roamjs.com` to be able to access my database again). Tried with default settings and either `{all}` or a specific page under `includes`.

**Comment by dvargas92495** [comment]
oh this is really bad. Is your graph particularly large? Not really clear where it would become unresponsive, but I could see some places where it could be slow. Would you be free for a call some time tomorrow so I could take a look at it running on your graph?

**Comment by tfiers** [comment]
Yes, sent you a DM on twitter

**Comment by dvargas92495** [comment]
Made some performance enhancements but still haven't solved the core issue, which is that we'll need to be able to query from web workers/in the background. In any case, should be much faster now for the core use cases
