### ISSUE TITLE
Calendar -- [Meet]() printed when there is no hangout link

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#658]
If there is no hangout link, nothing should be printed.
The other option, to skip it by using just {hangout} without an alias will stain the page with a huge ugly URL.

**Comment by dvargas92495** [comment]
this is with a custom format right?

**Comment by mkosma** [comment]
I'm seeing this as well, yes with a custom format. The fix I'd love to see is a {meeting} tag that includes [Meet]({link}) or [Zoom]({link}) the same way the default format does. (The default appears to include some enhancements beyond what's in the readme - caused a bit of confusion.) 

Maybe I'll just fork the repo and PR ...

**Comment by dvargas92495** [comment]
yes! happy to take a contribution!

**Comment by mkosma** [comment]
Cool! I think I have the code done, but I'm getting this error in trying to
test locally. Any idea what I'm missing? Guessing it's something in my
local node/npm config:

**Comment by mkosma** [comment]
looks like something for oAuth may be what's missing...

**Comment by dvargas92495** [comment]
`chrono is not defined` usually means no `npm install`. Have you installed dependencies locally?

**Comment by mkosma** [comment]
David, 

I spent some more time, removed all else in roam/js ...  looks like oauth is the culprit. 

Perhaps I need a GOOGLE_CLIENT_ ID / GOOGLE_CLIENT_SECRET to test the extension locally? Not sure if that would be my own or one that ties to roam-js-extensions, or where I need to set that.

**Comment by dvargas92495** [comment]
Ah yea, you're probably missing the google client id. This is public, and could be set by creating a `.env.local` file locally with the following values:
```
GOOGLE_CLIENT_ID=950860433572-rvt5aborg8raln483ogada67n201quvh.apps.googleusercontent.com
REST_API_URL=https://api.roamjs.com
```

The second line ensures that you hit the live RoamJS backend while testing the frontend extension

**Comment by mkosma** [comment]
That did it! Thanks. Also enhanced the custom formats a bit, making available to custom formats some of the prior enhancements to the default format.

monty
