### ISSUE TITLE
Calendar -- nested blocks don't appear

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#659]
For example, I want to get the event {link} nested:

- {summary} ({start:hh:mm} - {end:hh:mm}) [Meet]({hangout})
    - {link}

**Comment by dvargas92495** [comment]
Closed in https://github.com/dvargas92495/roamjs-google-calendar/commit/fda9eafab09d112bc723f4ecead15eaf6cfc856d
