### ISSUE TITLE
Calendar -- a labeled event pulled as "busy"

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#662]

**Comment by dvargas92495** [comment]
Were you logged in through the roam/js/google-calendar page?

**Comment by kvistgaard** [comment]
Well, most likely. The script pulled the titles of all other events.

**Comment by dvargas92495** [comment]
Does the google-calendar page display "Successfully logged in"? if not, it's possible for some events to have different visibility from others
