### ISSUE TITLE
Calendar -- subsequent imports duplicate

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#663]
They should update (ad new items or change hose changed in the meantime) but not duplicate new unless doing so will be very slow.

**Comment by dvargas92495** [comment]
slow is not as much of a problem as correctness. Updating would not be doable unless we mark extra information on each block about which were a google cal import and which weren't. What's the use case here? just re importing today if new items get added to your calendar same day?

**Comment by kvistgaard** [comment]
I had three events imported. Then modified one and added one. Imported again I got 7 events of which 2 duplicated and 1 in the current and old version and one Okay.

**Comment by dvargas92495** [comment]
Audit: Won't do - could revist with interest
