### ISSUE TITLE
Query tools gives and error and seem to slow down Roam

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#671]
- query-tools.js:1 Uncaught (in promise) TypeError: e.trim is not a function
    - at f (query-tools.js:1)
    - at Array.map (<anonymous>)
    - at query-tools.js:1
    - at Array.map (<anonymous>)
    - at Object.t.getAttrConfigFromUid (query-tools.js:1)
    - at t.getConfigFromPage (query-tools.js:1)
    - at d (query-tools.js:1)
    - at query-tools.js:1
    - at query-tools.js:1
    - at u (query-tools.js:9)
    - at Generator._invoke (query-tools.js:9)
    - at Generator.next (query-tools.js:9)
    - at n (query-tools.js:1)
    - at c (query-tools.js:1)
    - at query-tools.js:1
    - at new Promise (<anonymous>)
    - at query-tools.js:1
    - at query-tools.js:1
    - at Module.1236 (query-tools.js:1)
    - at r (query-tools.js:1)
    - at query-tools.js:1
    - at query-tools.js:1

**Comment by dvargas92495** [comment]
I just pushed a change to fix this issue last night. Are you still seeing the error after refreshing today?

**Comment by dvargas92495** [comment]
the fix yesterday should fix the error, but not the slowness. found the root of the slowness, going to fix asap

**Comment by dvargas92495** [comment]
Ok I think the performance fix should be live!
