### ISSUE TITLE
Mindmap - Issue

### ISSUE THREAD

**Issue by orkhan10** [dvargas92495/roam-js-extensions#673]
The Markdown File to reproduce the issue: [Course-Stock 3- Day and Swing Trading.md](https://github.com/dvargas92495/roam-js-extensions/files/6362434/Course-Stock.3-.Day.and.Swing.Trading.md)

When I am in the main page some of the block are shown like this:
![0FA6A099-B29F-4C2A-8120-3E1EA482826E](https://user-images.githubusercontent.com/18570936/115812057-103fe200-a3f1-11eb-9c57-478b23b88839.png)

As soon as I zoom in on the branch (Section 2), some of the problem goes away. (first rectangle is still problematic, while the second one is resolved)
![991F7974-7F15-463E-BF6A-23A2A631436D](https://user-images.githubusercontent.com/18570936/115812062-1209a580-a3f1-11eb-84f0-c5a41160ceaf.png)

**Comment by dvargas92495** [comment]
hm I'm not seeing the issue on my end: 
![image](https://user-images.githubusercontent.com/7143571/115974490-2487fa00-a52b-11eb-948c-f2b5166faa35.png)

Might be something conflicting on your end. Do you have time for a call to help debug? https://calendly.com/dvargas92495/roamjs

**Comment by dvargas92495** [comment]
Resolved over call, an issue with ending new lines
