### ISSUE TITLE
[Bug] sort-references.js significantly slows down roamresearch

### ISSUE THREAD

**Issue by wogong** [dvargas92495/roam-js-extensions#677]
Several days ago, I found it took several seconds to load a page after clicking the link, which was not normal.
Performance tab in Chrome DevTools shows the lag was caused by sort-references.js. (Function Call: total time 2.25s)
I disabled sort-references.js and finally got rid of the lag.

**Comment by dvargas92495** [comment]
Do you know which function it was from the dev tools? If you use the extension on the test branch (`https://roamjs.com/656/sort-references`) you'll get a source mapped version that might give more hangup on where the lag is

**Comment by wogong** [comment]
The following information maybe not accurate for I am not familiar with the DevTools. (All copied from Performance tab in Chrome DevTools)

```
observerCallback
Total Time 2.17 s
Self Time 0
Function observerCallback @ sort-references.ts:154

DailyNote
Total Time 830.77 ms
Self Time 0
Function DailyNote @ sort-references.ts:85

DailyNoteDescending
Total Time 667.25 ms
Self Time 0
Function DailyNoteDescending @ sort-references.ts:110
```

**Comment by dvargas92495** [comment]
Cool that's super helpful. And I'm assuming that you have a default sort configured either on the page or globally? how many linked references are on the 2 second page?

**Comment by wogong** [comment]
I am not sure where the configuration is. The js I use under `roam/js` is 

```
var old = document.getElementById("sort-references");
if (old) {
  old.remove();
}

var s = document.createElement("script");
s.src = "https://roamjs.com/656/sort-references.js";
s.id = "sort-references";
s.async = false;
s.type = "text/javascript";
document.getElementsByTagName("head")[0].appendChild(s);
```

As for the number of linked references,  around 30 pages for above testing. I believe it's not that much.

The weird thing is the lag is appeared several days ago, before that it worked well without any sensable lag. So I suspect some changes lead to this.

Thanks for your work, I am glad this can be helpful.

**Comment by dvargas92495** [comment]
ah ok, I'm going to assume no attributes are configured then

**Comment by dvargas92495** [comment]
I pushed out a change yesterday. If you switch back to the main version `https://roamjs.com/sort-references.js`, are you still seeing performance issues?

**Comment by dvargas92495** [comment]
going to close, happy to reopen if still experiencing issues
