### ISSUE TITLE
Grammarly

### ISSUE THREAD

**Issue by dvargas92495** [dvargas92495/roam-js-extensions#693]
Be able to use the Grammarly extensions (or API) to read the entire Roam page instead of individual blocks

**Comment by palladion** [comment]
Hi David, found out that Grammarly currently works only on the block level if your block has a certain length. Short one-liner sentences don't trigger the plugin. ProwritingAid works even on short block, but unfortunately also only on the block.

**Comment by dvargas92495** [comment]
Audit: Won't do
