### ISSUE TITLE
Tag Cycle Extension Should Cycle Through The Raw Text Instead of Surrounding The Raw Text With [Brackets]

### ISSUE THREAD

**Issue by shanrauf** [dvargas92495/roam-js-extensions#704]
(I'll submit the PR for this if you'd like and you think this behavior should be added)

With the Tag Cycles extension, you're generally cycling between a set of pages (e.g [[TODO]], [[DONE]]). To create this cycle with the extension, I would write out the title as text (as opposed to with [[double brackets]]):

Ctrl+ENTER

- 
- TODO
- DONE

However, what if I change my TODO page's title to something else? (e.g [[Enqueued]]) If I change that page title to Enqueued, my cycling won't work as intended because it'll still use the [[TODO]] page.

The simple solution would be to cycle through the raw text instead of forecfully putting [[brackets]] around the text. Example:

Ctrl+ENTER

- d
- [[TODO]]
- [[DONE]]
- asdf random text to replace [[DONE]]

Since people are already using the extension probably, it would break their systems to switch to something like this, but maybe we could add a setting to toggle this? (maybe have a RAW keyword similar to the HASH keyword??) I'd be willing to submit this PR.

In any case, thanks for the hard work, this extension solves my problem extremely well.

**Comment by shanrauf** [comment]
My apologies, there LITERALLY is the feature I'm describing already in the extension and I just didn't read the docs hard enough... Thanks for the hard work haha

**Comment by dvargas92495** [comment]
haha glad you found it!
