### ISSUE TITLE
Article -- not able to import HTML from legal publications

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#705]
Example: https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32019R0773&from=EN

**Comment by dvargas92495** [comment]
when trying out locally, it seems like there are 1734 blocks to import but Roam has a limit of 300 per minute currently. Is that what you're seeing?

**Comment by kvistgaard** [comment]
No, for me just the first few blocks are imported (haven't counted but not more than 20) and that's all that happens.

**Comment by dvargas92495** [comment]
Audit: Won't do
