### ISSUE TITLE
Page synonyms crashing Roam

### ISSUE THREAD

**Issue by dunjack** [dvargas92495/roam-js-extensions#706]
Is anyone else finding an issue with Page Synonyms crashing the entire Roam itself?

**Comment by dvargas92495** [comment]
Yes this is a known Roam bug. For now, the workaround is found in this last paragraph on the https://roamjs.com/docs/extensions/page-synonyms page:

![image](https://user-images.githubusercontent.com/7143571/119687898-8cc14880-be15-11eb-9c18-246fc0efd75d.png)

**Comment by dunjack** [comment]
Aw man. That's brilliant. Thanks man!

Are there any plans for a Graph wide synonyms?

**Comment by dvargas92495** [comment]
How so?

**Comment by dunjack** [comment]
To use your example from the Demo.
On a Demo page, I can choose to has **task**, **Tasks**, and **Task** all link to the **Task**-page

So _Page Synonyms_ is really aptly named - it does what it says on the tin.

I was wondering if there was a way to do this across an entire Graph of Pages with a given Tag.
i.e. **task**, **Tasks**, and **Task** would link to the **Task**-page on the **Demo**-page, but also a completely separate page e.g. **Not-a-Demo**-page.

For me, this comes in handy as a clinician researcher that commonly uses abbreviations in my field.
For example, I would want **age-related macular degeneration** and **amd** and **AMD** to all be aliases for **AMD**. 
At present, I include them all into a single page **age-related macular degeneration (AMD)**, which can get quite distracting when you start referencing drug compounds such as **anti vascular endothelial growth factor (anti-VEGF)**

So this has utility for me, but how feasible is it and is it on the horizon?

**Comment by dunjack** [comment]
Also, what is your preferred method of support?
Patreon? add to the Roam/js fund challenge?

**Comment by dvargas92495** [comment]
Ah so you're basically asking if with one click, it would auto alias _all_ blocks in your graph? While possible, this could be a pretty expensive operation, and might even run into Roam's 300 block edit per minute limit.

To support directly, we accept sponsorships on https://roamjs.com/contribute! Each extension's documentation page also has a place to contribute.  If you see a specific project you'd like to see implemented, you could commit to funding the project, and won't be charged until the project is complete

**Comment by dunjack** [comment]
Right. I can see how it doesn't make sense to upscale this version of the solution.

Thanks for your time and contribution coming your way - what you do is very much appreciated!
