### ISSUE TITLE
Could you please support multiple oauth for roam/js/twitter feed?

### ISSUE THREAD

**Issue by JimmyLv** [dvargas92495/roam-js-extensions#722]
https://github.com/dvargas92495/roam-js-extensions/blob/334649488a9e5beb0ed4b3c6e726c2db6173945e/src/components/TwitterFeed.tsx#L89-L96

**Comment by dvargas92495** [comment]
Would you want the feed to import from all accounts, or for you to choose one of the accounts

**Comment by JimmyLv** [comment]
> Would you want the feed to import from all accounts, or for you to choose one of the accounts

Thanks for the reply, I think it's better to add an Accounts tab in the popup modal, then the user can select to import which feeds' tweets?

**Comment by dvargas92495** [comment]
Makes sense to me!

**Comment by JimmyLv** [comment]
wow! I just tried it and love it! 

And it seems no chance to import multiple accounts' feeds at once? Actually, after I choose one account and import tweets, then there is no chance to import another account again, 😂

**Comment by dvargas92495** [comment]
That is.... a great point 🤦 

I'll add a command palette command that could open the Twitter Feed

**Comment by JimmyLv** [comment]
@dvargas92495 cool~ it's an awesome idea to open Twitter Feed via command palette!
