### ISSUE TITLE
Google Drive Extension - Rendering No Preview for Images & PDF

### ISSUE THREAD

**Issue by harshadwaj** [dvargas92495/roam-js-extensions#723]
I browsed through the code and it looks like there is some issue getting the correct MIME type. It always goes to the 'Unknown File' path. No preview is rendered even for images or PDFs.
![WlsCtTEFlX](https://user-images.githubusercontent.com/22823838/124051305-96b31880-da5f-11eb-955b-5ee3f5a7027d.gif)

**Comment by dvargas92495** [comment]
the latest version simply failed to deploy https://github.com/dvargas92495/roamjs-google-drive/actions/runs/969862956.

Should be fixed now! https://github.com/dvargas92495/roamjs-google-drive/runs/2958333446

**Comment by harshadwaj** [comment]
Work perfect now! Thanks very much.
