### ISSUE TITLE
Google Drive Extension - Image/PDF Preview Keeps Spinning

### ISSUE THREAD

**Issue by harshadwaj** [dvargas92495/roam-js-extensions#724]
The image and pdf preview keeps spinning for big files. After testing with several file sizes, it looks like only those files greater than ~100kb has this issue. Smaller files preview fine. All image types has this issue. For pdf, this limit is little more than images (~200kb).

![image](https://user-images.githubusercontent.com/22823838/125179954-9244e780-e237-11eb-959d-e7249e01df50.png)

**Comment by harshadwaj** [comment]
Got some more details. Its throwing this exception for each preview:
Uncaught (in promise) RangeError: too many arguments provided for a function call: main.js:2:2908817

**Comment by dvargas92495** [comment]
Check out the latest version by refreshing!
