### ISSUE TITLE
Google Drive Extension - (Enhancement) Customizable Preview Frame Size

### ISSUE THREAD

**Issue by harshadwaj** [dvargas92495/roam-js-extensions#725]
The latest change of 'min-width: 100%' stretches the image full width and small images gets stretched rending in poor quality. It would be good to have the customizable preview frame size just like other Roamjs extensions.

**Comment by dvargas92495** [comment]
the latest change made max-width 100%: https://github.com/dvargas92495/roamjs-google-drive/commit/c15d235cc1e27f2037109c3252fc834d0b74304c#diff-b01f9f7ebba9029d9ded74f2001aa51bbb248ec0f32e2599096ad68cef7a4c53R78

in any case, I'm fully booked on client projects to take on enhancements. PRs welcome!

**Comment by dnlmc** [comment]
+1 on this one when possible (or if some1 wants to name their bounty price 😎 )

**Comment by dvargas92495** [comment]
Fix should be live
