### ISSUE TITLE
replaceTagText function does not support double-byte character

### ISSUE THREAD

**Issue by run-ze** [dvargas92495/roam-js-extensions#726]
left is what it returns now, right is what it should return
![image](https://user-images.githubusercontent.com/7091451/126638082-0c618af4-d966-4336-ab1e-332ba269fe8c.png)

roam can only parse double-byte character surrounding with `[[ ]]`
![image](https://user-images.githubusercontent.com/7091451/126637769-04f07656-5a0a-4b26-baab-515d424b8f0d.png)

**Comment by dvargas92495** [comment]
wow that's crazy. Thanks for the fix!

**Comment by dvargas92495** [comment]
Could you open a pull request against the repo?
