### ISSUE TITLE
Presentation -- support structuring above slide level

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#728]
Currently, the allowed structure is:
- {{slides}}
  - {slide}

So there is no way to organize slides or simply turn an existing page into a presentation without "flattening" at the slide level

It would be nice to have
- {{slides}}
  - {section} ((not visible as slide unless it is {title}
    - {slide}

It would be nice if there are many levels of sections if there is a way to do it without too much effort to show which is the slide level.

**Comment by dvargas92495** [comment]
Moved to #745
