### ISSUE TITLE
Tally extension does not update graph - only takes initial value

### ISSUE THREAD

**Issue by jmatthewpryor** [dvargas92495/roam-js-extensions#731]
The documentation for the Tally extension says:

> To save a value, or set an initial starting value for the counter, create a child block with the specified value.

But the code only takes its initial value from the graph - there is not updating of the graph

Likely needs
```
 window.roamAlphaAPI.updateBlock({
        block: { uid: blockUid, string: value },
      });
```
somewhere in TallyCounter.tsx

**Comment by dvargas92495** [comment]
This was intentional - users who initally requested this feature did not want to update the saved counter value upon updating. Setting the inital value involves manually editing the child block

**Comment by jmatthewpryor** [comment]
NP - perhaps just an update to the docs for the extension then

**Comment by dvargas92495** [comment]
What's the inconsistency? The snippet you blockquoted seem to align with current behavior

**Comment by jmatthewpryor** [comment]
the way I read it left me with the impression that if I added a sub-block, then the value would get saved. I guess you can interpret it either way, but perhaps clearer to just say that updates via the UI are not saved to the graph - so it's clear

**Comment by dvargas92495** [comment]
Doc changes Should be live
