### ISSUE TITLE
SVG embed

### ISSUE THREAD

**Issue by jbnv** [dvargas92495/roam-js-extensions#733]
Roam currently does not have any easy way to embed SVGs and no direct way to let SVG code live in a graph and render an SVG graphic from SVG code living in the graph.

*Proposed remedy:* A new `{{svg:BLOCKUID}}` command, where `BLOCKUID` is the UID for a block that contains an `html` code block containing the SVG code.

*Future enhancements:* The ability to pass arguments to the command, particularly a `scale` argument, so that the same SVG can be rendered multiple times in a graph but customized as needed.

**Comment by dvargas92495** [comment]
Audit: Won't do - Could revisit with resurfaced interest
