### ISSUE TITLE
SPARQL extension: Property value configuration

### ISSUE THREAD

**Issue by jbnv** [dvargas92495/roam-js-extensions#734]
> All property values, which are entities (people, places, and things as opposed to numbers and dates ) will be created (or reused if existing) as page references and their matching Wikidata item URI will be inserted as value of same as:: attribute, the same way as the property.

This results in the creation of a lot of pages and blocks that have little or no utility in the graph. It would be nice to be able to specify that certain attributes are not brought into the graph or are just brought in as data without creating a new page (f a page exists, go ahead and make a reference).

**Comment by kvistgaard** [comment]
Use options:
Create page reference for Wikidata
[ ] Properties
[ ] Values

Currently, it is both, which could remain the default, but one or both can be switched off to avoid bulking the graph.

So, I'd suggest, configuring the default in the setting and having these two as options in the pop-up.

**Comment by jbnv** [comment]
This could also be another pop-up (or wizard page) after the extension gets the data saying "We found these attributes, what do you want to do with them?" and for each one, [ ] Link to page [ ] No link [ ] Discard. Reading defaults from the configuration. This would actually be quite helpful as there's currently no way of knowing what data is being added to your graph until after the extension creates all of the blocks and pages (~8 blocks for each attribute value).

**Comment by dvargas92495** [comment]
Audit: Won't do - Could revisit if interest resurfaces
