### ISSUE TITLE
SPARQL extension: Bug(?): Numbers and dates

### ISSUE THREAD

**Issue by jbnv** [dvargas92495/roam-js-extensions#735]
> All property values, which are entities (people, places, and things as opposed to numbers and dates ) will be created (or reused if existing) as page references and their matching Wikidata item URI will be inserted as value of same as:: attribute, the same way as the property.

I don't know if this is a bug, but numbers and dates are in fact created as page references rather than literals. Numbers should just be literals. Dates come in as raw timestamps. Would help to Roamify them to DNP page references.

**Comment by kvistgaard** [comment]
Yes, this is a bug but I thought it was fixed.

**Comment by jbnv** [comment]
Apparently not. 

![image](https://user-images.githubusercontent.com/5308164/135462145-652ca03e-1de0-4fd6-95a5-c5fc57c51581.png)
