### ISSUE TITLE
Add navigation tools to pages for time periods

### ISSUE THREAD

**Issue by jbnv** [dvargas92495/roam-js-extensions#736]
I have a lot of time-based data in my graph, with pages for:

* Years (`\d\d\d\d`)
* Months (`\w+ \d\d\d\d` where `\w+` is "January", "February", etc.)
* Seasons  (`\w+ \d\d\d\d` where `\w+` is "Winter", "Spring", etc.)
* Decades  (`\d\d\d0s`)
* Parts of decades (`\w+ \d\d\d0s` where `\w+` is "Early", "Middle" or "Late")

To facilitate navigation among these pages, I create blocks with page references for the next/previous period and parent/child periods. These pretty much all have to be created manually. Even with SmartBlocks, the process is manual, results in a lot of page references that exist only for navigation, and is just hideous:

![RR year page](https://user-images.githubusercontent.com/5308164/135422541-b103cb9c-af79-4cb3-88b2-54200fa7e7db.png)

Proposal: An extension that detects time-period pages and automatically adds a bar with navigation to related pages, something like this: 

![time bar mock](https://user-images.githubusercontent.com/5308164/135422574-7d23c63f-1c34-483f-8119-9062593b213f.png)

**Comment by dvargas92495** [comment]
Have you checked out https://roamjs.com/doc/extensions/weekly-notes? I'd prob add features to that extension for this

**Comment by jbnv** [comment]
I don't see how this request fits congruently into that extension.

**Comment by dvargas92495** [comment]
> An extension that detects time-period pages and automatically adds a bar with navigation to related pages, something like this

Weekly notes is an extension that detects time-period pages (weeks) and automatically adds a bar of buttons with navigation to related pages (prev, next)

Your proposal afaict is to expand this to include other time periods besides week and to include navigation across time periods as well

**Comment by jbnv** [comment]
I'm all for an extension that provides a comprehensive approach to working with time-based pages and organizations of data.

**Comment by jbnv** [comment]
What would you say is a fair price for this functionality? I'm open to the possibility of funding it myself. I tried developing it myself but ran into problems with the DOM.

**Comment by dvargas92495** [comment]
Audit: Won't do - Could revisit if interest resurfaces
