### ISSUE TITLE
Feature Request - Make todo-trigger optional on Daily Notes Page

### ISSUE THREAD

**Issue by JustinHatchett** [dvargas92495/roam-js-extensions#740]
I'd love to see an option for the [todo-trigger extension](https://roamjs.com/docs/extensions/todo-trigger) to be disabled on the daily notes page.

For my use case, on my daily page, I have lots of tasks that come in via SmartBlock (routines, etc.) but when ticking them off I obviously already know what day they belong to so it's a bit redundant since my trigger includes today's date. I love the use of the trigger elsewhere in Roam to keep track of what I did that day so something like this would be perfect.

Let me know if there are any questions about this use case and thanks for all of the awesome work @dvargas92495!

**Comment by dvargas92495** [comment]
implemented with new`{now:skip dnp}` template option
