### ISSUE TITLE
[bug] serendipity adds reminders multiple times

### ISSUE THREAD

**Issue by wizzard0** [dvargas92495/roam-js-extensions#742]
Hi, trying the Serendipity plugin. Great idea, but a bit inconvenient in that it adds way too many blocks to the daily page. Always multiples of the number I set in the settings.

That is, if I set the count to 3, it might add 6 or even 15 blocks. If I set it to 2, then it would be 4, 6, 8 etc.

Currently I just set the count to 1, but would appreciate if I could set a fixed number :)

Also would be nice to be able to group all of them under one block - repeating tags seems a bit wasteful %)

upd: screenshot with count=1, in case it helps (can't find any specific logs in browser console). Reproduces with Chrome and Safari alike.
![image](https://user-images.githubusercontent.com/424619/146764145-7af52ae8-57e4-4035-91b3-f73be44a2eff.png)

**Comment by wizzard0** [comment]
Oh and also examples show a configuration panel while I always see just a regular page. This is not a problem but might help with diagnostics I guess

![image](https://user-images.githubusercontent.com/424619/146765803-1a58fe6d-9512-4942-a64c-d0fa0dc16881.png)

**Comment by dvargas92495** [comment]
This repeating behavior typically happens when using Roam across multiple devices. Is that the case in your situation?

**Comment by wizzard0** [comment]
Yes and no - one laptop is enough. But I do always keep multiple Roam tabs open as new ones open too slow

**Comment by dvargas92495** [comment]
Could see that happening in that case as well. The only way around it would be to keep track of it in our own backend since it'll be a single source of truth. Smartblocks do this, have you checkout out the RANDOMBLOCKMENTION commands in smartblocks?

https://roamjs.com/extensions/roamjs-smartblocks

**Comment by wizzard0** [comment]
> our own backend

localstorage is synchronous, and since last date is already tracked, shouldnt it be enough?

Thanks for the smartblocks suggestion, I started from it initially but find it to be overcomplicated %)

**Comment by dvargas92495** [comment]
I would think so. Do you have a consistent set of steps that reproduce the issue that I could try to replicate it on my end?

**Comment by wizzard0** [comment]
well... I'd say it's enough to open multiple windows in Chrome side by side, but also I can't understand when exactly it adds the blocks so the STR right now sounds like "open 2 windows and wait up to 24h" :\

**Comment by dvargas92495** [comment]
Wasn't able to reproduce with multiple chrome windows. Would you be able to record a loom?

**Comment by dvargas92495** [comment]
pushed a change awhile ago attempting to address
