### ISSUE TITLE
[feature request] serendipity - insert subblock

### ISSUE THREAD

**Issue by wizzard0** [dvargas92495/roam-js-extensions#743]
I use a template like this for journaling in Roam:
```
- #plan
  - do A
  - do B
- #later
  - idea C
    - counter-argument D
  - idea E
(...)
```
and if I add #later to the serendipity filter, it seems that it adds only the blocks tagged with "#later" directly, while reading the documentation I initially understood the logic as "insert random subblock of #later".

Tagging every subblock makes sense for todo/done, for more involved tag combinations it gets repetitive fast (and eats valuable screen space)

Is it possible to change the block selection logic so that a block C, D or E would also get considered for #later too?

**Comment by dvargas92495** [comment]
Block `counter-argument D` should currently be considered for `#later`. Just ran this on my end: 
![image](https://user-images.githubusercontent.com/7143571/147486550-53e6f385-a676-475c-ab91-7f8a47b16e04.png)

**Comment by wizzard0** [comment]
Interesting. Maybe I was just unlucky a few times in a row ))
