### ISSUE TITLE
 [Feature Request] [Google Drive] Ability to populate the uploaded filename as the parent

### ISSUE THREAD

**Issue by harshadwaj** [dvargas92495/roam-js-extensions#744]
The current file uploads are working wonderfully well. Kudos to that. This is a feature request to make it look better.

**Current behavior:**
The uploaded file is rendered in its own block. It does not have the ability to be minimized. It gets a child when the size is altered.

**Desired behavior:**
When a file is uploaded, the following structure is generated at that point

• filename of the uploaded file | or a pattern from config | blank, if nothing else works
   • rendered file
      • custom layout data

Optional config: ability to minimize by default on upload

**Advantages:**
1. File name gets indexed and is searchable
2. Files can be minimized making it clean with files names at the top. Easy to view when there are multiple files.

**Comment by dvargas92495** [comment]
Closing in favor of the focused repo
