### ISSUE TITLE
 ALT+SHIFT+I keyboard shortcut not work to automatically import the article from the link.

### ISSUE THREAD

**Issue by JimmyLv** [dvargas92495/roam-js-extensions#747]
- If there is already an article link in a block, you could use the ALT+SHIFT+I or the OPT+SHIFT+I keyboard shortcut to automatically import the article from the link.

related code: https://github.com/dvargas92495/roam-js-extensions/blob/master/src/entries/article.ts#L62

the use case video:

https://user-images.githubusercontent.com/4997466/160266827-4327afa4-8088-4e96-b920-cd7acc3f4609.mp4

**Comment by dvargas92495** [comment]
Closed with 91485dea59c0b18f7efa7692be13a2b8c7762848
