### ISSUE TITLE
Serendipity - Add CSS class

### ISSUE THREAD

**Issue by LaurenaRehbein** [dvargas92495/roam-js-extensions#748]
I'm enjoying the Serendipity extension but would like to be able to edit the CSS for the output. Would it be possible to add CSS selectors to the Label, etc?

**Comment by dvargas92495** [comment]
The label is just a Roam tag, so it should already be selectable with CSS

**Comment by LaurenaRehbein** [comment]
@dvargas92495 I was trying to do that, but don't see anything that is unique to the generated block, and is standard each day: 

![https://d.pr/i/JyuFAs](https://d.pr/i/JyuFAs+)
Full Image: https://d.pr/i/JyuFAs 

Am I missing it?

**Comment by LaurenaRehbein** [comment]
Maybe added here?

https://github.com/dvargas92495/roam-js-extensions/blob/master/src/entries/serendipity.ts#L354

`const container = b.closest(".rm-block-main");`

Could become: 

`const container = b.closest(".rm-block-main .rm-block-serendipity");`

I am only a beginner coder but would be happy to set this up as a PR if I am on the right track here.

**Comment by dvargas92495** [comment]
ah you are using a plain text label. If you use a tagged reference, you'd be able to select it, like `#Thoughts`:

![image](https://user-images.githubusercontent.com/7143571/163250279-74d46eeb-54c5-4b5d-a77d-ec13d1db3557.png)

The block isn't generated by RoamJS, just written to Roam itself. the line you referenced wouldn't add a selector, it's simply looking for the block with that selector. `closest` is a GET not a WRITE

**Comment by LaurenaRehbein** [comment]
Ah, got it! Thank you! Marking as Closed.
